"use client";
import { useState } from "react";
const serverAddress = "dvoid.minehut.gg";
function CopyAddress({ label = "Copy IP" }: { label?: string }) {
  const [copied, setCopied] = useState(false);
  async function copy() { try { await navigator.clipboard.writeText(serverAddress); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } }
  return <button className="button button--green" type="button" onClick={copy}>{copied ? "Copied!" : label}</button>;
}
export default function Home() { return <main>
  <header className="topbar"><a className="brand" href="#top" aria-label="Dvoid home"><span className="brand-cube" />DVOID</a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#worlds">Worlds</a><a href="#begin">Start here</a></nav><a className="discord-link" href="#community">Community <span aria-hidden="true">↗</span></a></header>
  <section className="hero" id="top"><div className="hero-void" aria-hidden="true"><i className="block block--one" /><i className="block block--two" /><i className="block block--three" /><i className="island island--one" /><i className="island island--two" /><i className="island island--three" /></div><div className="hero-content shell"><p className="eyebrow"><span className="pulse" /> Java server · Online now</p><h1>MAKE SOMETHING<br /><em>OUT OF NOTHING.</em></h1><p className="hero-copy">A custom void-survival world built around chance, discovery, and the things you dare to bring home.</p><div className="hero-actions"><CopyAddress label="Copy server IP" /><a className="button button--dark" href="#begin">How to play <span aria-hidden="true">↓</span></a></div><p className="server-address"><span>PLAY</span> {serverAddress}</p></div><div className="hero-strip">RANDOM DROPS <b>✦</b> CUSTOM DUNGEONS <b>✦</b> DAILY VERGE <b>✦</b> BUILD THE VOID <b>✦</b></div></section>
  <section className="intro section shell" id="about"><div className="section-kicker">WELCOME TO THE FRACTURE</div><div className="intro-grid"><h2>YOUR FIRST BLOCK<br />IS ONLY THE <span>BEGINNING.</span></h2><div><p>Every Dvoid player begins above an endless drop. A random item arrives every ten seconds. What you build with it is up to you.</p><p>Echo everyday items with <code>/dupe</code>, then earn the rare things: dungeon keys, relics, Marks, and a place in the world.</p></div></div></section>
  <section className="systems" id="worlds"><div className="shell"><div className="systems-heading"><div><p className="section-kicker">THE LOOP</p><h2>MORE THAN A<br /><span>SKYBLOCK.</span></h2></div><p>Start simple. Find your route. The void gets bigger when you do.</p></div><div className="card-grid"><article className="feature-card feature-card--drops"><span className="card-number">01</span><div className="pixel-icon pixel-icon--box" /><h3>RANDOM DROPS</h3><p>A new useful item every ten seconds. No kits. No shopping-cart start.</p><span className="card-tag">MAKE YOUR LUCK</span></article><article className="feature-card feature-card--dungeon"><span className="card-number">02</span><div className="pixel-icon pixel-icon--gate" /><h3>KEYED DUNGEONS</h3><p>Take a party through custom runs, fight bosses, and crack open rare caches.</p><span className="card-tag">RISK &amp; REWARD</span></article><article className="feature-card feature-card--verge"><span className="card-number">03</span><div className="pixel-icon pixel-icon--rift" /><h3>THE VERGE</h3><p>A daily-resetting resource world with public delves, incursions, and secrets.</p><span className="card-tag">A NEW REALITY DAILY</span></article></div></div></section>
  <section className="journey shell" id="begin"><div className="journey-art" aria-hidden="true"><div className="portal"><span /></div><div className="ground" /></div><div className="journey-copy"><p className="section-kicker">FIRST FRACTURE</p><h2>FIND YOUR WAY<br />THROUGH THE <span>VOID.</span></h2><ol><li><strong>01</strong><span><b>Join the server</b><small>Use Java Edition and connect with dvoid.minehut.gg.</small></span></li><li><strong>02</strong><span><b>Claim your first drop</b><small>Stay alert—your next building block is never far away.</small></span></li><li><strong>03</strong><span><b>Choose your route</b><small>Build, explore the Verge, or chase your first dungeon key.</small></span></li></ol><CopyAddress label="Copy server IP" /></div></section>
  <section className="community" id="community"><div className="shell community-inner"><div><p className="section-kicker">BRING A FRIEND</p><h2>THE VOID IS BETTER<br />WITH <span>PEOPLE IN IT.</span></h2></div><div className="community-card"><span className="online-dot" /> <b>PLAY DVOID</b><p>Guilds, parties, trades, arena fights, and shared expeditions await.</p><a className="button button--light" href="#top">Start playing <span aria-hidden="true">↑</span></a></div></div></section>
  <footer className="footer shell"><a className="brand" href="#top"><span className="brand-cube" />DVOID</a><p>Not an official Minecraft product. Not approved by or associated with Mojang or Microsoft.</p><div><a href="#about">About</a><a href="#begin">Play</a><a href="#community">Community</a></div></footer>
</main>; }
